### ISSUE TITLE
Include a component between ``` sections

### ISSUE THREAD

**Issue by kuworking** [mdx-js/mdx#1096]
If I want to add a repeated code within `<pre><code>` tags in my `mdx` component, I'd say this is not possible right now

```js
export const Code = <div>......</div>

` ` `js
{Code]
` ` `

another time

` ` `js
{Code]
` ` `

and another time

` ` `js
{Code]
` ` `

```

So that if I want to repeat the code, I need to copy-paste the code in all places

If this is actually not possible, it would be a nice feature to add

**Comment by wooorm** [comment]
MDX = MD (- HTML) + JSX. So, sticking with Markdown where possible, such as in code blocks, makes sense tome.

In fact, not “rendering” expressions is often useful, so that you can actually talk about expressions:

`````markdown
```
{1 + 1}
```
````

Now, if want expressions in code, you can use tags:

`````markdown
<pre><code>{asdasd}</code></pre>
````

(you may need some enters around the expression in MDX@1, but the above should work well in MDX@2).
