### ISSUE TITLE
MDX needs to map some camelcase properties to what React expects

### ISSUE THREAD

**Issue by laurieontech** [mdx-js/mdx#1148]
We are passing along `xLinkHref` when React expects `xlinkHref`.

Example of the problems is causes can be seen in [this Gatsby issue](https://github.com/gatsbyjs/gatsby/issues/25013).

**Comment by wooorm** [comment]
Fixed on next. See also: https://github.com/mdx-js/mdx/pull/1048 for a related prop

**Comment by laurieontech** [comment]
Awesome, @johno and I were speculating on whether or not v2 parsing would handle this.

**Comment by wooorm** [comment]
Hi all! I’m going to close this as it landed on the `main`, the (now default) branch we’re using to gear up to the MDX@2 release.

The reason is so that it’s more clear which issues still need to be solved already and don’t require further work.

Expect another `next` release soonish, which might include it, or maybe it’s already released as a beta!

For more info, see <https://github.com/mdx-js/mdx/issues/1041>.
