### ISSUE TITLE
Fenced code blocks

### ISSUE THREAD

**Issue by streamich** [mdx-js/mdx#118]
Have you considered using fenced code blocks?

    ```jsx
    import Graph from './components/graph'
    ```
    
    ## Here's a graph
    
    ```jsx
    <Graph />
    ```

What are the benefits/drawbacks of this approach?

**Comment by timneutkens** [comment]
It's overhead when writing, also it's unexpected behaviour, since you expect a code block to be turned into a code block.

**Comment by jxnblk** [comment]
We explored using fenced code blocks with an earlier implementation but felt like it was out of scope for this particular spec, which is heavily geared towards rendering pages like you would in a blog.

Code blocks are great for when you want to use standard markdown syntax, but add extra functionality in the rendered result – e.g. for documentation purposes – because sites like GitHub.com will still render the code fence.

We'll likely bring back some of that functionality in a separate package for use in Compositor apps. Hope that makes sense!

**Comment by timneutkens** [comment]
Compositor is @jxnblk and @johno's company: https://compositor.io/
