### ISSUE TITLE
Fix Windows tests for the v2 parser

### ISSUE THREAD

**Issue by johno** [mdx-js/mdx#1182]
AFAICT from looking at the GitHub Actions CI, Windows tests appear to be failing based on [`\r\n` newlines](https://github.com/mdx-js/mdx/pull/1077/checks?check_run_id=901033888)

**Comment by wooorm** [comment]
The “problem” is that remark always outputs `\n` instead of `\r\n`. Which I think is fine behavior.

Adding `expectedDoc = expectedDoc.replace(/\r\n/g, '\n')` [here](https://github.com/mdx-js/mdx/blob/f59b174e828538353dbec2189ec361c8f0bd0817/packages/remark-mdx/test/index.js#L1482) should allow that?

**Comment by wooorm** [comment]
Windows tests are working now, although it does still seem like we’re DDoSing the yarn/npm registry and thus sometimes failing tests 🤷‍♂️
