### ISSUE TITLE
Weird output on using Nextjs <Link> 

### ISSUE THREAD

**Issue by eKhattak** [mdx-js/mdx#1194]
### Subject of the issue
Styling doesn't work if you use `next/link` in `.mdx` file without adding any normal words before `<Link...`
Here's an example

This works
![input](https://user-images.githubusercontent.com/37709578/88776168-1032ee80-d19f-11ea-90ea-93a0244690ab.png)
![output](https://user-images.githubusercontent.com/37709578/88776219-2345be80-d19f-11ea-8579-1dd9bf25abf3.png)

But this doesn't work

![bug input](https://user-images.githubusercontent.com/37709578/88776284-35bff800-d19f-11ea-9e59-ac2b3b4fac8a.png)
![buggy output](https://user-images.githubusercontent.com/37709578/88776322-3d7f9c80-d19f-11ea-8a8d-894b60c466ef.png)

### Your environment

*   **OS**: Microsoft Windows 10
*   **Packages**: 
```
    "@mapbox/rehype-prism": "0.3.1",
    "@mdx-js/loader": "0.20.3",
    "@mdx-js/mdx": "0.20.3",
    "@mdx-js/tag": "0.20.3",
    "@next/bundle-analyzer": "9.1.4",
    "@next/mdx": "8.1.0",
```
*   **Env**: Node v12.18.3, NPM v6.14.6, Chrome v84

### Steps to reproduce

- Clone the [repo](https://github.com/vercel/next-site/)
- Go to `pages/learn/basics/create-nextjs-app/index.mdx` (or any other `.mdx` file)
- Add the following code 
```
import Link from 'next/link'
<Link href="/"><a>**example**</a></Link>. 
```

### Expected behaviour
Styling should Work Properly

### Actual behaviour
Styling doesn't work on that line

**Comment by johno** [comment]
He @eKhattak, thanks for opening up an issue! This is a result of the v1 parser thinking that the entire block is JSX when a line _begins_ with JSX. You'd need to add a space before your Link to trigger the inline tokenization. This is something that will be fixed in v2 (#1077).

Since it's not something we plan on fixing in v1, and is fixed in v2 (which has a canary release), I'm going to close this issue.
