### ISSUE TITLE
Two blank lines within a fenced code block terminates ordered list and breaks code block

### ISSUE THREAD

**Issue by epbarger** [mdx-js/mdx#1316]
### Subject of the issue
Fenced code blocks within a number bullet point break if they contain more one new-line in a row.

### Your environment

*   **OS**: macOS Mojave 10.14.4
*   **Packages**: `@mdx-js/mdx@1.6.4`, via `"gatsby-plugin-mdx": "^1.2.6"`
*   **Env**: yarn 1.22.4, gatsby 2.23.1

### Steps to reproduce
Nest a fenced code block under a number bullet point, with two blank lines in a row within the code block. One blank line does not cause this issue.

````markdown
1. Test
   ```
   broken


   example
   ```

Plain text after the numbered bullet point
````

### Expected behaviour

I would expect this to work fine, parsing the code block correctly and keeping the entire block nested under the numbered bullet point.

### Actual behaviour

The second new line appears to cause the parser to end the bullet point, breaking the code block. The ending triple backticks will then start a new code block, causing chaos with the rest of the page

![Screen Shot 2020-10-29 at 3 41 01 PM](https://user-images.githubusercontent.com/2780987/97624236-374ac780-19fd-11eb-8604-4981c5f6aac3.png)

**Comment by wooorm** [comment]
@epbarger Could you check if this is solved in MDX@2? (see the open issues about that for more info). That’s a big rewrite that might solve this. And there’s another change coming to that’d definitely solve this, by using the new micromark parser in remark

**Comment by wooorm** [comment]
Hi all! I’m going to close this as it landed on the `main`, the (now default) branch we’re using to gear up to the MDX@2 release.

The reason is so that it’s more clear which issues still need to be solved already and don’t require further work.

Expect another `next` release soonish, which might include it, or maybe it’s already released as a beta!

For more info, see <https://github.com/mdx-js/mdx/issues/1041>.
