### ISSUE TITLE
@mdx-js/runtime and mdx-embed return empty components

### ISSUE THREAD

**Issue by johackim** [mdx-js/mdx#1489]
### Subject of the issue

I test mdx-js/runtime with mdx-embed, and It return empty components.

### Your environment

*   **OS**: Linux
*   **Packages**:

"react": "^17.0.1"
"react-dom": "^17.0.1"
"@mdx-js/react": "^1.6.22"
"@mdx-js/runtime": "^1.6.22"
"mdx-embed": "^0.0.19"

*   **Env**: node (v12.21.0)

### Steps to reproduce

```node
import React from 'react';
import { renderToString } from 'react-dom/server';
import { MDXProvider } from "@mdx-js/react";
import MDX from '@mdx-js/runtime';
import { Tweet } from 'mdx-embed';

const components = { Tweet };

const content = `
# Hello, world!
<Tweet tweetLink="PaulieScanlon/status/1232982448310497286" />
`;

const result = renderToString(
    <MDXProvider components={components}>
        <MDX>{content}</MDX>
    </MDXProvider>
);

console.log(result);
```

### Expected behaviour

Have an iframe with a Tweet embedded

### Actual behaviour

It return an empty component : `<div data-testid="general-observer" class="mdx-embed"><div style="height:0;width:100%"></div></div>`

**Comment by ChristianMurphy** [comment]
Trying this in codesandbox, mdx is returning a component as expected https://codesandbox.io/s/crimson-haze-rbqq6
This is likely an issue with `mdx-embed` https://github.com/PaulieScanlon/mdx-embed/issues/220

**Comment by johackim** [comment]
Hello @ChristianMurphy, thanks for your response !

I completely forgot to precise that I run mdx-runtime directly with nodejs without browser.

I develop a cli tool to convert mdx components to html.

[Here the code with codesandbox](https://codesandbox.io/s/mdx-jsruntime-with-mdx-embed-d73lg)

Thanks for your time.

**Comment by ChristianMurphy** [comment]
> I completely forgot to precise that I run mdx-runtime directly with nodejs without browser.

That's fine as well.
MDX is a language, it's goal is to take MDX files and conver them to JS which can be used with React (or Vue, or Preact).
Which it did, you can see that `mdx-embed` was called in your sandbox:

```
<h1>Hello, world!</h1><div data-testid="general-observer" class="mdx-embed"><div style="height:0;width:100%"></div></div>
```

How react or the library used chooses to handle static component rendering isn't something that MDX has control over.
If you take MDX out of the mix here, and call mdx-embed's `Tweet` component directly: https://codesandbox.io/s/mdx-jsruntime-with-mdx-embed-forked-v5q82 the result is the same, MDX is not the root cause of the issue.

**Comment by johackim** [comment]
Exact ! Thank you very much, have a good day ;)
