### ISSUE TITLE
Improve examples documentation

### ISSUE THREAD

**Issue by YousefED** [mdx-js/mdx#1582]
Hi! Just looking into MDX

It took me a while to get the example (syntax-highlighting running). I tried `yarn && yarn start` as mentioned in the readme, but after a while I figured I also needed to run `yarn build` in the rootdirectory beforehand.

Hope this helps others, maybe good to clarify in the docs as well!

**Comment by ChristianMurphy** [comment]
Thanks @YousefED!
That's likely because the packages are listed as part of the workspace which leads it to use the local (unbuilt) copy over the npm published (built) version.
https://github.com/mdx-js/mdx/blob/87756784c7148b8d6da5911fcd60d1db38df9dc5/package.json#L11-L12
Updating the docs to note the build step would be a welcome addition!

**Comment by wooorm** [comment]
Sorry for the trouble.
I went through all examples to make sure they worked: https://github.com/mdx-js/mdx/pull/1645.
