### ISSUE TITLE
Playground: Codemirror instance crashes sporatically

### ISSUE THREAD

**Issue by KuangAnthony** [mdx-js/mdx#1791]
### Subject of the issue

When typing or backspacing, sometimes Codemirror will crash.

![Playground-MDX](https://user-images.githubusercontent.com/61532649/139755364-4e9a4e1c-912c-4705-b803-dc193e2998e3.png)

### Your environment

*   Linux Mint 
*   Chrome latest 

### Steps to reproduce

1. https://v2.mdxjs.com/playground
2. Type or backspace fast, should get error within a few minutes
3. I have no idea what causes this

### Expected behaviour

No error thrown

### Actual behaviour

Error thrown, though recoverable through ResetErrorBoundary

**Comment by ChristianMurphy** [comment]
The issue is coming from the CodeMirror component.
The root of issue is that `value` is a controlled property and the selection is an internally managed state.

The issue happens while an edit is made at the exact moment a state update is being processed, at that particular moment `value` and `selection` can get out of sync, and the `selection` range can be outside the new `value`, causing the exception `RangeError: Selection points outside of document`.

The issue has always been there, but became more visible when debouncing was added in https://github.com/mdx-js/mdx/pull/1758
Previously the main thread was locked by rendering making it harder to cause the error (along with hard to edit in general :sweat_smile: )

Some possible solutions:
1. replace this particular React CodeMirror integration with another
2. replace CodeMirror with another editor
3. Split the codemirror content text and the render text into two slices of state and only debounce the render text (the issue may persist but would happen less often)

**Comment by AnthonyKuang** [comment]
Very late update, but upgrading to latest `next` seems to make this work for my case, same implementation as the docs. Not sure why.

**Comment by ChristianMurphy** [comment]
:thinking: interesting, do you mean `@mdx-js/mdx` next?
If so the site should already be running next, and the issue may be resolved?

**Comment by KuangAnthony** [comment]
I was using `xdm`, `mdx-js/mdx` is also working well now. I can't replicate the same issue anymore 👍🏼
