### ISSUE TITLE
Add in docs how to install

### ISSUE THREAD

**Issue by bsides** [mdx-js/mdx#1907]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Right now, the homepage doesn't show how to install this package. Then you go to "Getting Started" page and it doesn't have a way to install it either. I know it's obvious for you guys, but this info is crucial and the info is nowhere to be found, not even in the README of the github project.

### Solution

`npm install package` somewhere in the top. 

It's the first thing one should do after checking pre-requisites.

### Alternatives

Yarn, pnpm, etc.

**Comment by ChristianMurphy** [comment]
@bsides sorry you ran into a spot of trouble.
Some context, mdx is a mono-repo, there are several projects.
There isn't a single install instruction, because it isn't a single project.

Each package has an example on how to install in its own readme.
* https://github.com/mdx-js/mdx/tree/main/packages/esbuild#install
* https://github.com/mdx-js/mdx/tree/main/packages/loader#install
* https://github.com/mdx-js/mdx/tree/main/packages/mdx#install
* https://github.com/mdx-js/mdx/tree/main/packages/node-loader#install
* https://github.com/mdx-js/mdx/tree/main/packages/preact#install
* https://github.com/mdx-js/mdx/tree/main/packages/react#install
* https://github.com/mdx-js/mdx/tree/main/packages/register#install
* https://github.com/mdx-js/mdx/tree/main/packages/remark-mdx#install
* https://github.com/mdx-js/mdx/tree/main/packages/rollup#install
* https://github.com/mdx-js/mdx/tree/main/packages/vue#install

**Comment by bsides** [comment]
I understood, thank you.
