### ISSUE TITLE
giving elements custom ID while rendering in html

### ISSUE THREAD

**Issue by Besuf** [mdx-js/mdx#1942]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

So I am using an mdx files in nextjs website to render some rich text contents. It's cool being able to render elements like headings and paragraph elements with your custom Components. The Problem though arises when you have a scenario when you have certain section of a paragraph you want to render differently as the custom component you made for the paragraph renders for all paragraph components.

### Solution

 So That's where giving custom id for elements comes in in my opinion. There should be a way to enable us give some elements a custom id so that we can later identify them in our html and style them as needed.

### Alternatives

I really don't see any other way to be honest

**Comment by ChristianMurphy** [comment]
Adding attributes to content is supported through a plugin that customizes the syntax tree (you can learn more about syntax trees and plugins here: https://unifiedjs.com/learn/)
For example, creating a rehype plugin like

```js
function idGenerator() {
  return "example";
}

function rehypeAddIdToParagraphs() {
  return function transformParagraphs(tree) {
    visit(tree, { type: "element", tagName: "p" }, (node) => {
      node.properties = { ...node.properties, id: idGenerator() };
    });
  };
}
```

Runnable example: https://codesandbox.io/s/example-of-rehype-plugin-in-mdx-djkjho

<details>
<summary>source from sandbox</summary>

```jsx
import { useEffect, useState } from "react";
import * as runtime from "react/jsx-runtime";
import { evaluate } from "@mdx-js/mdx";
import { visit } from "unist-util-visit";

const mdxContent = `
export const planet = 'World'

# Hello, {planet}!

* list
* item

paragraph one

paragraph 2
`;

function idGenerator() {
  return "example";
}

function rehypeAddIdToParagraphs() {
  return function transformParagraphs(tree) {
    visit(tree, { type: "element", tagName: "p" }, (node) => {
      node.properties = { ...node.properties, id: idGenerator() };
    });
  };
}

function useMDX(content) {
  const [exports, setExports] = useState({ default: runtime.Fragment });

  useEffect(() => {
    evaluate(mdxContent, {
      ...runtime,
      rehypePlugins: [rehypeAddIdToParagraphs]
    }).then((exports) => setExports(exports));
  }, [content]);

  return exports;
}

export default function App() {
  const exports = useMDX(mdxContent);
  const Content = exports.default;
  return <Content />;
}
```

</details>

That said, that said I don't think that adding id will solve the stated problem of

> The Problem though arises when you have a scenario when you have certain section of a paragraph you want to render differently as the custom component you made for the paragraph renders for all paragraph components.

Because either:
* all the id will be the same, which doesn't let you consistently target a specific paragraph
* or the ids are randomly generated and will drift as content is added
In both situations adding an id won't let you consistently style a specific paragraph.

You may want to consider using a JSX wrapper instead, an example in mdx:

```mdx
normal unstyled paragraph

<p className="style-me">styled paragraph</p>
```

which would give a consistent `class` which could be targeted from the stylesheet.
