### ISSUE TITLE
Markdown Image gets wrapped inside Paragraph

### ISSUE THREAD

**Issue by ludwigfrank** [mdx-js/mdx#208]
This might be the intended behaviour, anyways it seems unintended to wrap an image inside the paragraph component.

e.g.
```
![Image of Yaktocat]({URL})
```

becomes 
```
<ParagraphComponent>
    <ImageComponent/>
<ParagraphComponent/>
```

**Comment by silvenon** [comment]
That’s how Markdown behaves, AFAIK. Maybe writing HTML code instead will prevent the paragraph component.

**Comment by johno** [comment]
A while back I [wrote a plugin](https://www.npmjs.com/package/remark-unwrap-images) to unwrap images when desired (@silvenon is correct in that being the default behavior of md).

Looks like I haven't pushed that package to GitHub yet, will do so today.

**Comment by silvenon** [comment]
Eventually you will be able to write JSX in order to avoid wrapping in paragraphs. Currently this causes bugs, as described in https://github.com/mdx-js/mdx/issues/246#issuecomment-422076927, but we're working on it. Once that is resolved you will be able to write `<img src="..." />` and it will not be wrapped in a paragraph.

To avoid tracking multiple issues of the same problem, I'm closing this in favor of #246.
