### ISSUE TITLE
Using jsx in Markdown link adds {` ... `} to the start and end of the link, which breaks the link

### ISSUE THREAD

**Issue by schlichtanders** [mdx-js/mdx#2173]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

2.1.5

### Link to runnable example

https://codesandbox.io/s/boring-wescoff-g2tknl?file=/pages/index.mdx

### Steps to reproduce

Just add the following small snippet to your mdx:

```mdx
export const variable = "helloworld"
{`${variable}`} [link]({`${variable}`})
```
You can see that while the first jsx works as intended, the second within the link is completely ignored.

### Expected behavior

Jsx should also work within a markdown link

### Actual behavior

jsx does not work at all within a markdown link

**Comment by wooorm** [comment]
Your example is quite different from the code sandbox?

Anyway, you can’t use braces in `()` of a link. MDX is not a templating language. It adheres to the grammar of markdown. You can’t use emphasis, strong, whatever inside the `()` either.

**Comment by schlichtanders** [comment]
I was doing it first in the sandbox and then adapted some namings to standalone.

I don't understand how allowing braces within Markdown links breaks the grammer of mdx. We already can use jsx braces within html despite jsx does not adhere to the grammer of html. So why is it an argument that jsx is no markdown to not support jsx within mdx?

I lost here.

-------

There is no use case for using emphasis, strong, whatever inside a markdown link, because it is a link. Still it is very useful to use jsx within a markdown link, because it happens that my link needs to be composed from variable names.

It would be really helpful if you can explain in more detail, why this is not planned to be implemented in MDX. I do not understand your reasoning so far, and It would be a really useful feature.

**Comment by wooorm** [comment]
A pity that you ignore the alternative, which is is fine.

A) This isn’t HTML. B) That’s not what’s happening. We parse separate tags. In places where other markdown things are supported as well. Later we match them together.

If a heading is allowed, “block” level JSX tags (or expressions) are allowed.
If emphasis is allowed, “inline” level JSX tags (or expressions) are allowed.

JSX/expressions are not added in places where other markdown of similar content types is allowed either. It’s not in code. Not in frontmatter. Not in titles. Not in character references.

> There is no use case for using emphasis ...

There is a use case for people having actual braces in their links. They already do that in the wild. Your proposal will crash existing MDX.

---

MDX is not a templating language. In templating languages, the “expressions” in language A are compiled away, which generates some string of language B.
No parser for language B can understand a document in language A.
We couldn’t make a proper AST because things might overlap.

**Comment by schlichtanders** [comment]
Thank you so much for the explanation. (the alternative I was already using as a workaround - I was really interested in why this is not possible within markdown links)

> There is a use case for people having actual braces in their links. They already do that in the wild. Your proposal will crash existing MDX.

This one is an impressively strong argument on its own. Thank you so much for sharing it, as I really was not aware of this ambiguity.

Also thank you for the other explanations.
