### ISSUE TITLE
need to set an option for `remark plugins` to be used before the "remark-mdx" in the pipeline

### ISSUE THREAD

**Issue by talatkuyuk** [mdx-js/mdx#2236]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

In the remark eco system, some plugins process the character "<" or ">" or "<<" or ">>", in order to, for example, make guillemets turning "\<\<abc\>\>" to "«abc»" . [link to remark-fix-guillemets](https://github.com/zestedesavoir/zmarkdown/tree/master/packages/remark-fix-guillemets)
(for guillemets there is need to use a `remark-textr` plugin also.)

Here is another issue for `remark-smartypants` [the link](https://github.com/silvenon/remark-smartypants/issues/71)

If the `format` is `md`, there is no problem. I can produce the quillemets.
But, if the `format` is `mdx`, the string "\<\<abc\>\>" cause error in the mdx files.

I digged the issue. In the code of @mdx-js/mdx I found that: [link](https://github.com/mdx-js/mdx/blob/main/packages/mdx/lib/core.js#L101)

```js
const pipeline = unified().use(remarkParse)

if (format !== 'md') {
  pipeline.use(remarkMdx)
}

pipeline
  .use(remarkMarkAndUnravel)
  .use(remarkPlugins || [])
  ...
```

Means that, `remark-mdx` comes prior to `remarkPlugins` and used just after `remark-parse`, and this causes the issue.

### Solution

If the `remark-mdx` would used after the `remarkPlugins` in the pipeline, there would be no problem.

### Alternatives

In this point, if it is not convenient to use the `remark-mdx` after the `remarkPlugins`, we can set another option like *`remarkPluginsBeforeMdx`* something like that, in order some plugins to be used before `remark-mdx` in the pipeline. In that case the plugins like `remark-fix-guillemets` and `remark-smartypants` could be useful even for `mdx` format markdown files.

**Comment by wooorm** [comment]
Hi Talat! This can’t happen, your solution/alternatives won’t work! Feel free to try it out locally, but here’s why:

a) Using the plugins you want before `remark-mdx` doesn‘t solve your problem, as it is a *syntax* extension, it changes how the parser works, and parsing always comes first. The other plugins are *transform* plugins, they work on the AST, they can’t work before parsing, because they need a parsed thing
b) if this was possible, this would break several users of MDX, `remark-mdx` must come before other syntax extensions.
c) `remark-fix-guillemets` can’t work with MDX, it depends on HTML nodes, MDX does not have HTML.
d) it’s by design that `<` is a syntax error in these cases in MDX. You can escape them for MDX (`\<\<`). `remark-smartypants` will see it then.

Conceptually though, it’s really intentional that `<` is unambiguous in MDX and either starts JSX or causes a parse error.

**Comment by talatkuyuk** [comment]
Ohh.. thank you for quick reply.
