### ISSUE TITLE
Use Frontmatter for imports.

### ISSUE THREAD

**Issue by johnhenry** [mdx-js/mdx#240]
Really awesome project. I think makes sense to separate imports from markup. One way to do this would be to use [frontmatter](https://jekyllrb.com/docs/frontmatter/) -- a concept made popular by Jekyll and a few other projects.

```markdown
---
import: { Chart } from '../components/chart'
---

# Here's a chart

The chart is rendered inside our MDX document.

<Chart />
```

I wonder if anyone else has thoughts on this?

**Comment by ChristopherBiscardi** [comment]
What problem does introducing a new syntax for imports that exists only in frontmatter solve? It's already possible to organize imports at the top of an mdx file if you want to and you could write a lint rule to enforce that too. Presumably it would still be possible to import at other locations in the mdx file (or are you also suggesting the removal of the standard JS import syntax?)

**Comment by johnhenry** [comment]
Honestly, I'm not sure if it solves a "real" problem. If someone wanted to start their file with "import { Chart } from '../components/chart'", it would be an issue; but again I acknowledge that this isn't a "real" problem. 
Yes, I am suggesting the removal of the standard JS import syntax.  Frontmatter would provide a semi-standardized method of importing. Because frontmatter is [customarily] used to provide variables to pre-processed markdown files, it seems like a good fit -- perhaps a missed opportunity.

**Comment by ChristopherBiscardi** [comment]
I'd be against that change without a strong use case tbh. We already use the AST to strip imports out and hoist them in gatsby-mdx so this is handled by tooling instead of manually by humans (and using JS import syntax means we can use babel to manipulate/process imports/exports). Introducing a new import syntax means creating and maintaining not only the new syntax but additional tooling to deal with it.

The only reason we have frontmatter support at all in gatsby-mdx is to ease migration of legacy markdown files and sites to mdx and I don't really see a need for frontmatter parsing in core mdx.

> Because frontmatter is [customarily] used to provide variables to pre-processed markdown files, it seems like a good fit -- perhaps a missed opportunity.

What specific opportunity is being missed here? mdx already supports both imports and exports in an arguably more flexible and [standardized](http://www.ecma-international.org/ecma-262/6.0/#sec-modules) way than the frontmatter approach would. Also, since mdx compiles to JS modules, the JS module import/export format is a natural fit and imports/exports don't have to be processed and transformed from the frontmatter syntax to the es module syntax for end-user use when importing an mdx file.

**Comment by silvenon** [comment]
Yeah, I don’t see a need for this either. That would be a new synax we’d need to implement and parse without a clear benefit. Import/export syntax takes care of everything already.

**Comment by jxnblk** [comment]
FWIW we decided against using front matter early on. I was originally in favor of it, but now think that MDX is much better without it. That said, it's not too difficult to set up your own custom loader in front of the mdx-loader if you want to use front matter in your project, as is done here https://github.com/c8r/x0/blob/master/lib/mdx-fm-loader.js
