### ISSUE TITLE
Missing "./package.json" in package.json "exports"

### ISSUE THREAD

**Issue by artuska** [mdx-js/mdx#2556]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Missing "./package.json" in package.json "exports":

```
"exports": {
   ".": "./index.js",
  "./internal-create-format-aware-processors": "./lib/util/create-format-aware-processors.js",
  "./internal-extnames-to-regex": "./lib/util/extnames-to-regex.js"
},
```

### Solution

Just add "./package.json" in package.json "exports" like that:

```
"exports": {
  "./package.json": "./package.json",
   ".": "./index.js",
  "./internal-create-format-aware-processors": "./lib/util/create-format-aware-processors.js",
  "./internal-extnames-to-regex": "./lib/util/extnames-to-regex.js"
},
```

### Alternatives

Just add "./package.json" in package.json "exports".

**Comment by ChristianMurphy** [comment]
Welcome @artuska! 👋 
I'm open to adding the package to the exports.
Could you expand a bit on _what_ you want out of that file? And _why_ or _how_ you want to leverage it?

**Comment by artuska** [comment]
This feature is related to the Vite issue — https://github.com/originjs/vite-plugin-federation/issues/357

**Comment by ChristianMurphy** [comment]
@artuska it looks like a bug in an abandoned module https://github.com/originjs/vite-plugin-federation/issues/597
And that it is no longer recommended https://github.com/originjs/vite-plugin-federation/issues/597#issuecomment-2395491268

Try migrating to https://github.com/module-federation/vite

I'd hold on making changes here because:
1. it's not clear why the package is needed by the tool in the first place
2. it's an abandoned tool, and I don't think it's a good idea to try to change the entire npm ecosystem to try to fix abandoned tools

**Comment by wooorm** [comment]
Paraphrasing the argument here, some unmaintained, uncommon, tool is broken and an error can disappear when we add `package.json` to exports. There are viable alternatives: migrating to a maintained alternative or patch-package. I don’t think that’s a good story for changing things here.

For me, it is intentional that `package.json`s are not part of the public API. We can have a discussion about adding them to all packages. We could test a small subset of course and it doesn’t have to be all at once. But still: I’m not convinced yet and that would be a whole discussion about trade offs, so more something for https://github.com/unifiedjs/rfcs or so.

That discussion would have little to do with the arguments here. So, closing this issue for now.
