### ISSUE TITLE
Make `export default () =>` and `Layout` a MDXAST/MDXHAST node

### ISSUE THREAD

**Issue by timneutkens** [mdx-js/mdx#273]
This way the user will be able to define it's own behavior around enabling, disabling and wrapping these features.

Eg https://github.com/mdx-js/mdx/pull/229 wouldn't be needed anymore, but could be a plugin. 

Another use case is hoisting the layout property using `hoist-non-react-statics`, a problem that you run into with Next.js is that you can't define `getInitialProps` on the layout component as it's not hoisted correctly.

cc @johno @silvenon

**Comment by silvenon** [comment]
Sometimes I get lost in this stuff, could explain this idea more? Do you mean that we could add an additional `export` node to, say, `mdx-ast-to-mdx-hast.js` which replaces the one we add in `mdx-hast-to-jsx.js`. Then instead of `skipExport` we can add a hast plugin which simply removes that node and people can add their own hast plugins to modify that node? But how? It's would just be a regular string.

**Comment by johno** [comment]
Superseded by #382
