### ISSUE TITLE
Feature Request: Add support for global component registration

### ISSUE THREAD

**Issue by viztor** [mdx-js/mdx#295]
story:
I want to let ordinary users use react component as if they were normal html tags.
content creator want to use mdx but we can't expect all writers to known javascript.

reason:
the idea is to enhance markdown so people aren't familiar with javascript (e.g. non-technical content creators, can still take advantage of it), thus make it more available to a broader audience.

for example, I would built up a website using gatsby. and there would be some component that I would want everybody to have access to.

the idea is also consistent with the original intent of design for markdown, which meant to help authors focus on content creation.

task:
global component registration and automatic locate\import。

**Comment by silvenon** [comment]
Can you show me some examples of how you would like this to work? I'm not sure I understand what you mean by "global component registration" and "automatic locate/import".

**Comment by ChristopherBiscardi** [comment]
In gatsby-mdx we're going to allow "global" components to replace the shortcode use case (which is what I think this issue is about). For example, the following wouldn't need an explicit import for the `Youtube` component to display a video.

```
# My thing

<Youtube hash="ai3ikoh"/>
```

We're going to do it in gatsby-mdx by injecting the imports for you (since we already handle a bunch of import manipulation), but I don't particularly see how it would fit into core. It feels like something higher level tools can support.

**Comment by silvenon** [comment]
That would be great! It sounds analogous to the `scope` prop in MDX runtime:

```jsx
import MDX from '@mdx-js/runtime'
import YouTube from '../components/YouTube'

const mdx = `
# Hello World!

<YouTube hash="ai3ikoh" />
`

const App = () => (
  <MDX
    scope={{ YouTube }}
    children={mdx}
  />
)
```

**Comment by ChristopherBiscardi** [comment]
yes, our [runtime is different](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/f4b81a46ab085465aa383fbf2bf626dee9bbfa1f/packages/gatsby-mdx/mdx-renderer.js) because we do the processing at build-time (so it's smaller), but we use the same scope concept to push the dependencies into the MDX renderer (although via context, not explicitly for most use cases). For our global support, we're going to spread the global scope into the local scope and use the combined scope. The global scope will be sourced via context from a wrapper at the root of the app and the local is sourced via context from a wrapper closer to the render site (like a page's wrapper or a wrapper for a component with a static query).

**Comment by ChristopherBiscardi** [comment]
@Ehesp see https://github.com/ChristopherBiscardi/gatsby-mdx/issues/138

There's a plan, and a way to achieve it today in the meantime.

**Comment by buz-zard** [comment]
You can achieve this by simple remark plugin via `mdPlugins` prop:

```
<MDX
  mdPlugins={[
    () => tree => {
      tree.children.unshift({
        type: 'import',
        value: 'import Clock from "react-live-clock";',
      });
    },
  ]}
/>
```

For relative imports you'll need to resolve path when bundling.

**Comment by ChristopherBiscardi** [comment]
@Ehesp  @viztor We shipped this in gatsby-mdx as the `globalScope` option as of v0.3.2. I wrote [a post on it](https://www.christopherbiscardi.com/post/towards-shortcodes-for-gatsby-sites) as well from the perspective of shortcodes

**Comment by erquhart** [comment]
This feels like the way to go for most MDX applications, Gatsby or otherwise. Any thoughts on how this works with the MDX spec? I ask because a tool's claim of "MDX support" would seem to entail the ability to process MDX docs, import/export and all.

**Comment by erquhart** [comment]
@ChristopherBiscardi ^^

**Comment by ChristopherBiscardi** [comment]
@erquhart The feature in gatsby-mdx was specifically defined in a way that would let us grow it to a point where we can also introduce it to core MDX after playing with it, getting feedback, and figuring out how the API should work in all cases. We have not submitted it to the core yet, but will in the future.

If you have feedback for specific use cases (I noticed you work on netlify-cms) here is a good place to put them (or feel free to file issues against the gatsby-mdx implementation as well to further develop the API). The ways I've implemented other CMS extensions is to [use sandpack](https://github.com/CompuIves/codesandbox-client/tree/master/packages/sandpack). One thought I've had is to ship a utility package to work with MDX files specifically for tools like gatsby-mdx and CMS extensions.

Does that answer your question?

**Comment by erquhart** [comment]
Thanks Chris, it does. I wanted to make sure that the MDX still has flexibility regarding imports - sounds like it does. Regarding utilities, I was mostly expecting to find tools to bridge from MDAST to MDXAST, but we can do that manually if necessary, at least for initial support.

**Comment by johno** [comment]
This will be supported in v1 via the MDXProvider thanks to @ChristopherBiscardi's custom pragma implementation.
