### ISSUE TITLE
v16: super before this access

### ISSUE THREAD

**Issue by ChristopherBiscardi** [mdx-js/mdx#319]
I think I forgot a `super()` in the MDXContent class from #309. Not sure why it didn't pop up before when running tests, etc.

![image](https://user-images.githubusercontent.com/551247/48803847-ec2fc200-ecc7-11e8-8698-dbc2446d3463.png)

**Comment by tujoworker** [comment]
Thanks a lot for Your work @ChristopherBiscardi so far!
Since Version **0.16.1** of `@mdx-js/mdx` i get this error: `MDXContent cannot be invoked without 'new'`

**gatsby-mdx** is using your work as a peer dependency `import MDXRenderer from 'gatsby-mdx/mdx-renderer'`


Hope this is not too much as a pain to fix ☺️

**Comment by ChristopherBiscardi** [comment]
@tujoworker Check out https://github.com/ChristopherBiscardi/gatsby-mdx/issues/192

I have it working locally but need to find a moment to push it up, merge and release.

**Comment by ChristopherBiscardi** [comment]
(just to make it clear for any other maintainers, this is a gatsby-mdx runtime issue and not a mdx-js/mdx issue)
