### ISSUE TITLE
Generates class while README suggested functional component

### ISSUE THREAD

**Issue by weyert** [mdx-js/mdx#373]
### Subject of the issue

If you try to generated code from a string of Markdown using the `@mdx-js/mdx`-package it's returning a class component instead of a functional component as suggested in the README file.

### Your environment

ProductName:	Mac OS X
ProductVersion:	10.14.2
BuildVersion:	18C54

@mdx-js/mdx: 0.16.6
Node: v11.6.0
NPM: 6.5.0
Yarn: 1.12.3

### Steps to reproduce

I am trying to the following:
```
  let transformedFunction = mdx.sync(`
  # Hello, MDX
  
  I <3 Markdown and JSX
  `)
```

this returns:

```

export default class MDXContent extends React.Component {
  constructor(props) {
    super(props)
    this.layout = null
  }
  render() {
    const { components, ...props } = this.props

    return <MDXTag
             name="wrapper"
             
             components={components}><MDXTag name="h1" components={components}>{`Hello, MDX`}</MDXTag>
<MDXTag name="p" components={components}>{`  I <3 Markdown and JSX
`}</MDXTag>
           </MDXTag>
  }
}
```

### Expected behaviour

I would expect it returns the suggested code as listed in the README file:
```
export default ({components, ...props}) => <MDXTag name="wrapper"  components={components}><MDXTag name="h1" components={components}>{`Hello, MDX`}</MDXTag>
<MDXTag name="p" components={components}>{`I <3 Markdown and JSX`}</MDXTag></MDXTag>
```

### Actual behaviour

See above

**Comment by weyert** [comment]
I am getting a feeling some behaviour has changed between 0.15 vs 0.16

**Comment by johno** [comment]
Yeah, great catch. The documentation needs to be updated 😬. In v0.16 we switched from a functional component to a class component.

**Comment by johno** [comment]
Of course 😄.

The reason is the previous functional version evaluated layouts inline of the render function. This caused the layout component to remount on every render if you declared a layout as an inline function like so:

```jsx
# Hello, world

export default props => <div {...props}>
```

This caused unnecessary rerenders, but more importantly also broke things like hash links due to remounting.

By using a class-based component we memoize it as an attribute in the class. Though, I suspect we can now do this more cleanly with [`React.memo`](https://reactjs.org/blog/2018/10/23/react-v-16-6.html) which was released in v16.6 🤷‍♀️ 

Hope that helps!

**Comment by weyert** [comment]
Thank you, I will have to see how I can make my macro work with the class definitions!

**Comment by johno** [comment]
Going to close this since it's being tracked in #389 as well. v1 will move back to a functional component.
