### ISSUE TITLE
hints for typescript usage

### ISSUE THREAD

**Issue by dfee** [mdx-js/mdx#435]
### Subject of the issue

It took a few minutes for me to figure out how to use this with typescript, so I figured i'd share it here.

### Your environment

MacOS, React 16.8.2...

### Steps to reproduce

Create a MDX declaration file:
```ts
// src/mdx.d.ts
declare module "mdx.macro" {
  export function importMDX(
    path: string,
  ): Promise<{ default: React.LazyExoticComponent }>;
}
```

```ts
// src/about-page.tsx
import { importMDX } from "mdx.macro";
import React, { lazy, Suspense } from "react";
import { PrimaryLayout } from "src/components";

const Content = lazy(async () => importMDX("./terms-of-service.mdx"));

export type AboutPageProps = {};

export const AboutPage = (props: AboutPageProps) => (
  <PrimaryLayout>
    <Suspense fallback={<div>Loading...</div>}>
      <Content />
    </Suspense>
  </PrimaryLayout>
);
```

**Comment by johno** [comment]
Thanks for sharing! We should probably get this in the docs. Would you be interested in a PR?

**Comment by dfee** [comment]
Probably better than that would be to have a declaration file for this (and perhaps something global for `.mdx` files as described [here](https://mdxjs.com/getting-started/typescript) -- for those who aren't using CRA).

Are you all interested in adding typings?

**Comment by johno** [comment]
Yeah I suppose that wouldn't hurt. I don't use Typescript myself so I'm not sure how that works, though I believe @timneutkens does.

**Comment by johno** [comment]
Since this repo doesn't use TS we'd love for someone to add typings to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). We'll gladly accept a PR for a more thorough guide of MDX + TS usage.

**Comment by ChristianMurphy** [comment]
https://github.com/mdx-js/mdx/pull/811

**Comment by Vadorequest** [comment]
I was also confused by usage of MDX within Next.js using TypeScript (.tsx files)

At first glance, I thought I just had to configure webpack and it'd use MDX within my .tsx files, but it's not the way it actually works.

The above example from @dfee is great for CRA, but won't work with Next because of `Suspense` which isn't SSR-compatible.

After various attempts, I eventually managed to make it work (locally, at least).

PR: https://github.com/UnlyEd/next-right-now/pull/98

---

Example:

```tsx
import React from 'react';
import { Jumbotron } from 'reactstrap';

import Content from './myMDXPage.mdx';

type Props = {}

const TSXWithMDXPage: React.FunctionComponent<Props> = (props): JSX.Element => {
  return (
    <Jumbotron
      className={'center'}
    >
      <Content />
    </Jumbotron>
  );
};

export default TSXWithMDXPage;
```

---
`myMDXPage.mdx`

```mdx
import { Button } from 'reactstrap';

# title 1
<Button>test</Button>

```

- [with-next example](https://github.com/vercel/next.js/blob/master/examples/with-mdx/next.config.js)
- https://mdxjs.com/getting-started/next#nextjs
