### ISSUE TITLE
Use dangerouslySetInnerHTML for static tags

### ISSUE THREAD

**Issue by IanChen83** [mdx-js/mdx#472]
### Subject of the issue

After transpiling mdx documents to react components, the code size are several times bigger than pure html code. This is because each rehype node becomes a `React.createElement` function call
(for example, `<h2>content</h2>` becomes
`React.createElement(MDXTag,{name:"h2",components:{},parentName:"p"},"content")`).

I think it would be great if there's an option to toggle the use of `dangerouslySetInnerHTML` for static tags. This way, when a rehype node and all of its descendents are normal HTML nodes, it can be packed to a single `React.Component`. Since normal HTML code are basically fixed at runtime, this transformation won't cause any problem (if the `components` props are fixed, too).

This feature is more useful if we want to use the same loader for markdown files and mdx files. The only way to load normal markdown files is through the use of markdown loaders and the `dangerouslySetInnerHTML` prop. This option allows MDX loader behave like a markdown loader.

I've created a [plugin](https://github.com/IanChen83/mdx-hast-reduction) for prototyping. However, because the way MDX transforms the `root` node, there're still many nodes that cannot be reduced. Therefore, I believe this option (if this feature is valid) should be built directly in the MDX instead of a plugin.

**Comment by johno** [comment]
Thanks for writing up this issue @IanChen83! Have you checked out the [custom pragma approach](https://mdxjs.com/blog/custom-pragma) in [v1](https://github.com/mdx-js/mdx/tree/v1)?

This pragma should have a reduction in bundle size, though likely not as much as using `dangerouslySetInnerHTML`. I don't think this approach should be used in core, though, because it would break downstream MDX libraries that rely on proper React elements as children. Additionally this approach is required for component composition and components that are dynamic at runtime. We can't guarantee that Markdown elements _are_ static. Ultimately that's part of its power 😉

That said, I think we should also have the ability to have a purely static output so I'd definitely consider making this an official MDX plugin.

**Comment by IanChen83** [comment]
Oh! I wrote the prototyping plugin 4 months ago and it seems in 4 month MDX changes a LOT.

Now, it looks like the custom pragma approach can truly connect the world of markdown and React, comparing with the `MDXTag` approach. If this is the case, I would say the `dangerouslySetInnerHTML` trick is not a good core feature.

> That said, I think we should also have the ability to have a purely static output

Yes, I agree with you that a static (or partially static) output would be a good transition between pure markdown and React.

**Comment by johno** [comment]
Yeah, we've been working hard! I'll go ahead and close this for now and we can address something more static-focused as a plugin down the road after v1 goes stable.

Thank you very much for digging in, writing a plugin, and opening up this issue!
