### ISSUE TITLE
export / import keywords break MDX runtime execution

### ISSUE THREAD

**Issue by medhir** [mdx-js/mdx#581]
## `export` / `import` keywords break MDX runtime execution

I've been playing around with MDX the past couple days, and was trying to prototype a live-code editing component in React. I noticed that trying to use the `import` or `export` keywords within a live-playground type component causes the component to break, as the `import` and `export` keywords throw a SyntaxError

- Without `export` keyword => 
<img width="1382" alt="Screen Shot 2019-05-18 at 10 18 23 PM" src="https://user-images.githubusercontent.com/5160860/57978096-028ab200-79bb-11e9-8d22-23c41d63c5be.png">

- With `export` keyword => 
<img width="1386" alt="Screen Shot 2019-05-18 at 10 31 49 PM" src="https://user-images.githubusercontent.com/5160860/57978191-cfe1b900-79bc-11e9-8971-2d95437900d4.png">

### Your environment

*   Mac OS X v10.14.4
*  "@mdx-js/mdx": "^1.0.19", "@mdx-js/react": "^1.0.16", "@mdx-js/runtime": "^1.0.19",
* Node v11.13.0, npm v6.7.0, tested on Chrome Version 74.0.3729.131 

### Steps to reproduce

Pass an MDX string to the MDX runtime component with an `export` or `import` keyword.

### Expected behaviour

`export const foo = 'foo'` should expose `foo` as a string value to be used within the MDX as a JSX value. 

### Actual behaviour

Within the client runtime, using these keywords causes parsing to break due to unexpected tokens. Is this a known issue with trying to implement the `export` or `import` statements client-side? I noticed I could repro the issue on MDX's site:

Adding `export` to this pane throws `SyntaxError: unknown: Unexpected token, expected "{"` and breaks the whole page (it goes blank).

<img width="494" alt="Screen Shot 2019-05-18 at 10 09 36 PM" src="https://user-images.githubusercontent.com/5160860/57978142-d7ed2900-79bb-11e9-966c-c5ef9cc87c46.png">

Likewise, adding an `export` in the playground throws a `ReferenceError`: 
<img width="1050" alt="Screen Shot 2019-05-18 at 10 24 46 PM" src="https://user-images.githubusercontent.com/5160860/57978163-35817580-79bc-11e9-8e21-7ece8ffe9486.png">

Overall, really cool project! Wondering if what I'm trying to achieve is currently possible or if there's some known limitation at this point. Cheers!

**Comment by johno** [comment]
I thought I responded to this issue a while ago, but it looks like I forgot to hit submit! 😞 

You can see now that the playground uses `remark-mdx-remove-imports` and `remark-mdx-remove-exports` to work around this limitation:

https://github.com/mdx-js/mdx/blob/f4d11d88614e3af83a13edc6dc7e9a4f7010efe9/packages/gatsby-theme-mdx/src/components/playground-editor.js#L8-L34

Granted that means that imports/exports won't actually be added to scope, but for something like `imports` it'd require a client side bundler anyway. I've opened up #698 to address your latter example where the export variable isn't being added to scope (since it's currently being naively removed).

Hope this helps!
