### ISSUE TITLE
typescript typings for @mdx-js/react

### ISSUE THREAD

**Issue by sw-yx** [mdx-js/mdx#616]
### Subject of the issue

typescript typings

```ts
declare module "@mdx-js/react" {
  import { ComponentType, StyleHTMLAttributes } from "react"

  type MDXProps = {
    children: React.ReactNode
    components: { wrapper: React.ReactNode }
  }
  export class MDXProvider extends React.Component<MDXProps> {}
}
```

just stubbed out a basic typings. this is of course incomplete bc it just meets my needs and i don thave time to do a complete one right now but i'd be happy to collaborate with people to make a good one.

**Comment by johno** [comment]
I've [added](https://github.com/mdx-js/mdx/commit/ffc896d004d4f4e21823ddcd27fda95b2d56a11f) this to the [TS docs](https://github.com/mdx-js/mdx/blob/master/docs/advanced/typescript.md).

Thanks for the addition @sw-yx!

Going to go ahead and close this for now since it isn't actionable for me at this point (I don't use TS). If anyone comes across this, we'd absolutely love more PRs and issues to help improve TypeScript support from the community. 🙏 ❤️ 🙏 ❤️

**Comment by ChristianMurphy** [comment]
https://github.com/mdx-js/mdx/pull/811
