### ISSUE TITLE
Extract babel plugin in remark-mdx to its own package

### ISSUE THREAD

**Issue by johno** [mdx-js/mdx#720]
Follow up on #719 when that is merged.

**Comment by Luiginator** [comment]
@johno I moved the plugin to its own package. Could you please take a look? Thanks! https://github.com/mdx-js/mdx/pull/826

**Comment by wooorm** [comment]
Hi y’all! I’m going to close this as it landed on the `main`, the (now default) branch we’re using to gear up to the MDX@2 release.

The reason is so that it’s more clear which issues still need to be solved already and don’t require further work.

Expect another `next` release soonish, which might include it, or maybe it’s already released as a beta!

For more info, see <https://github.com/mdx-js/mdx/issues/1041>.
