### ISSUE TITLE
RFC: Consolidate pre/code/inlineCode

### ISSUE THREAD

**Issue by johno** [mdx-js/mdx#743]
Having different nodes from remark/rehype is a bit confusing, especially now that one can differentiate by using `parentName`.

**Comment by ehowey** [comment]
Heads up that when I was running a11y checks on my site I am getting an error requiring tabindex="0" and overflow-y="auto", pops up when the code box is smaller than the viewport and scrolls.  Maybe an easy fix to include when making other optimizations.

**Comment by ehowey** [comment]
Now as I think about this more I realize this is actually trickier, because you wouldn't want every code block to be tabbable by default.  I was getting the accessibility error on a code block that had a very long line of code and was creating scroll bars on it.  I think I can maybe handle this a different way.

**Comment by wooorm** [comment]
@johno So, are you proposing dropping the `inlineCode` node, and going with mdast + jsx + expressions + imports + exports, only?

**Comment by johno** [comment]
Yeah, that's the proposal @wooorm, but after thinking about it I'm not sure it's worth the breaking change right now since it isn't really hard to support and has come pretty embedded in MDXProvider usage.

Might be something to put back on the table for v3.
