### ISSUE TITLE
MDXProvider not accepting components in 1.4.4

### ISSUE THREAD

**Issue by lannonbr** [mdx-js/mdx#768]
### Subject of the issue

So as of the latest version, the MDXProvider component is not applying components that are passed into it through the `components` prop.

### Your environment

*   **OS**: MacOS 10.14 & Windows 10 1903 (WSL Ubuntu 18.04).
*   **Packages**: @mdxjs/mdx 1.4.4 & @mdxjs/react 1.4.4
*   **Env**: Firefox 69, Node 10.x, yarn 1.16

### Steps to reproduce

Repro: https://github.com/lannonbr/MDXProvider-bug-repro

The repo is a fresh `gatsby new` of the blog theme starter. Then I added a `gatsby-browser.js` to add the component as such:

```jsx
import React from "react"
import { MDXProvider } from "@mdx-js/react"

export const wrapRootElement = ({ element }) => {
  return (
    <MDXProvider
      components={{
        h1: ({ children }) => <h4 style={{ color: "red" }}>{children}</h4>,
      }}
    >
      {element}
    </MDXProvider>
  )
}
```

### Expected behaviour

Should switch all `<h1>` tags to `<h4>` with red text

### Actual behaviour

Absolutely nothing. the provider doesn't seem to applying the new components.

**Comment by johno** [comment]
Thanks for opening an issue and creating a repro!

When I swap `wrapRootElement` with `wrapPageElement` it works. I _suspect_ this has to do with `gatsby-plugin-theme-ui` overriding at the root level as well so the component isn't being rendered (since Theme UI will also create an h1 and add to context).

At the very least this doesn't seem to be a bug in MDX core since the provider appears to be working as expected. This seems to be a bug in Gatsby and/or Theme UI because I'd expect the user's gatsby-browser to wrap _after_ a plugin's 🤔.

**Comment by johno** [comment]
Going to go ahead and close this for now since it isn't MDX core specific and an issue in Gatsby or Theme UI.
