### ISSUE TITLE
Inline comment directly after jsx block fails to parse.

### ISSUE THREAD

**Issue by mjhenkes** [mdx-js/mdx#784]
### Subject of the issue

Adding an inline md comment directly after an inline html/jsx block in a markdown file causes mdx to fail to parse.

Similar to this issue: https://github.com/mdx-js/mdx/issues/243

### Your environment

*   **OS**: macos
*   **Packages**: "@mdx-js/react": "^1.4.5",

### Steps to reproduce

ON the sample site, add an inline comment to the in html example.
```
# Below is a JSX block

<div style={{ padding: '10px 30px', backgroundColor: 'tomato' }}>
  <h2>Try making this heading have the color green</h2>
</div>
<!-- AUTO-GENERATED-CONTENT:END -->
```

🎉 BONUS POINTS for creating a [minimal reproduction](https://stackoverflow.com/help/mcve) and uploading it to GitHub.  This will get you the fastest support.  🎉

### Expected behaviour

The comment is ignored.

### Actual behaviour

Parsing fails.

**Comment by Danon** [comment]
Successful parse:
```mdx
<!-- Comment -->
<Component/>
```
```mdx
<Component/>

<!-- Comment -->
```

Failure:
```mdx
<Component/>
<!-- Comment -->
```
```mdx
<!-- Comment --><Component/>
```
```mdx
<Component/><!-- Comment --> 
```

**Comment by wooorm** [comment]
Heya, I’m working on a replacement for the current JSX parsing to solve many of the outstanding issues, like this one.

I have one Q about this: why should `<!--comments like this-->` be supported in MDX? We replace HTML with JSX, so wouldn’t it make more sense to only support `<>{/* comments like this */}<>`?

**Comment by Danon** [comment]
@wooorm Good question. I reckon MD doesn't have a syntax for comments, so we were left with HTML comment. Nor does JSX have comments, really.

I'm not sure about `<>{/* comments like this */}<>` since:
 - that's 10 characters of comment syntax (pragmatic? not sure)
 - That's not a JSX comment, actually. That's JS comment, inside `{}` syntax inside JSX inside MDX.

**Comment by wooorm** [comment]
Just circling back to report that the next branch supports my earlier idea, and you don’t need fragments, this works:

```
{/* comments like this */}
```

Which is one character less than HTML comments!

**Comment by wooorm** [comment]
Hi all! I’m going to close this as it landed on the `main`, the (now default) branch we’re using to gear up to the MDX@2 release.

The reason is so that it’s more clear which issues still need to be solved already and don’t require further work.

Expect another `next` release soonish, which might include it, or maybe it’s already released as a beta!

For more info, see <https://github.com/mdx-js/mdx/issues/1041>.
