### ISSUE TITLE
Multiple block quotes don't have line breaks

### ISSUE THREAD

**Issue by lex111** [mdx-js/mdx#828]
### Subject of the issue

There's no line break between 2 block quotes.

### Your environment

*   **OS**: Ubuntu 18.04
*   **Packages**: @mdxjs/mdx 1.4.4 & @mdxjs/react 1.4.4
*   **Env**: Chrome 77.0.3865.120, yarn 1.19.1

### Steps to reproduce

```
> 1st block quotes
> 2rd block quotes
```

### Expected behaviour

> 1st block quotes
> 2rd block quotes

### Actual behaviour

> 1st block quotes 2rd block quotes

**Comment by rbelow** [comment]
Hello @lex111 ! If you type the "Steps to reproduce" in a markdown file on VS Code and click on "Open Preview to the Side" you get the same exact behavior.

On the other hand if you use the "Steps to reproduce" on a GitHub comment you get the "Expected behavior".

> 1st block quotes
> 2rd block quotes

 :sweat_smile:

Would be interesting to know the opinion of an MDX project member.

BTW if you insert a line between block quotes in VS Code you get the "Expected behavior"

**Comment by wooorm** [comment]
This is a fact of markdown. To create separate paragraphs, add a blank line between them. Note that GitHub does that too. Only on issues/PRs/releases it doesn’t.

Solutions are:

```markdown
> 1st block quotes

> 2rd block quotes
```

> 1st block quotes

> 2rd block quotes

...or:


```markdown
> 1st block quotes
>
> 2rd block quotes
```

> 1st block quotes
>
> 2rd block quotes

**Comment by lex111** [comment]
:man_facepalming: 

![image](https://user-images.githubusercontent.com/4408379/76244143-8c598380-624a-11ea-81cd-84958fad2054.png)

On GITHUB:

> 1st block quotes
> 2rd block quotes

Random online Markdown editor: 

![image](https://user-images.githubusercontent.com/4408379/76244330-e78b7600-624a-11ea-8dad-30f9a230f902.png)
 

But it’s better to close this issue than try to fix it! :clap:

**Comment by lex111** [comment]
Sorry about that, then it would be nice to render line breaks in the MDX playground otherwise it leads to a misunderstanding.

**Comment by wooorm** [comment]
I don't understand, could you clarify what you propose?
