### ISSUE TITLE
Escaped Pipes (in tables) retain escape character (\)

### ISSUE THREAD

**Issue by riceboyler** [mdx-js/mdx#838]
### Subject of the issue

When using Markdown Table syntax, using the escape character (\) for pipes (|) does not remove the escape character when rendered. Example: 
![image](https://user-images.githubusercontent.com/2243596/68338183-2b088480-009f-11ea-8e07-c024c22c1c53.png)

This is *not* a place to ask questions.  For that, go to [Spectrum](https://spectrum.chat/mdx)

### Your environment

*   **OS**: MacOS 10.14
*   **Packages**: mdx-js 1.5.1
*   **Env**: Chrome 79, Node 12.11

### Steps to reproduce

Tried to create an mvce on CodeSandbox but that was met with frustration. Basically, create a simple component with a Markdown table and attempt to use an escaped pipe in that table:

```javascript
# Hello, world!

<Button>Here is a button</Button>

|Test|Test2|
|---|---|
|`testy \| testy` | testy |
```

### Expected behaviour

The pipe should be rendered without the preceding escape character

### Actual behaviour

The pipe is rendered prepended by the escape character.

**Comment by riceboyler** [comment]
To be fair, I think this bug may lie more in how unified.js handles escaped pipes, but I admittedly don't have enough experience with unified (or ASTs in general) to know.

**Comment by wooorm** [comment]
This indeed has to do with how remark-parse [interprets table cells](https://astexplorer.net/#/gist/037bc8ddbb2c1898094e1e5176a4ceab/21d8f975e2ab391d0cd97ff1d17c6a6d42a7e2c4) and is a bug there. The escape slash is a literal slash, instead of an escape. We’re working on a [replacement that has much better support for MDX](https://github.com/remarkjs/remark/issues/439).

If you’d like to support us to get there faster, and are able to, please [sponsor us on OpenCollective](https://opencollective.com/unified)!

**Comment by wooorm** [comment]
Sorry btw, forgot about this issue, but this is, horrible as that may sound, a feature instead of a bug. Escapes (`` # Hello, world! `\#` ``) and character references  (`` # Hello, world! `&amp;` ``) *do  not work* in code: https://spec.commonmark.org/dingus/?text=%23%20Hello%2C%20world!%20%60%5C%23%60

It’s what lets you embed HTML and other things inside code blocks without needing to double encode everything such as ~~`&lt;this&gt;`~~

**Comment by ThomasEhling** [comment]
Hi @wooorm 

Even though this issue is a few years old, our team still has the same issue today.

It's true that ```Escapes (#Hello, world!`\#`) and character references (#Hello, world!`&amp;``) don't work in code``` but the real problem here is that the table does not detect that the pipe character is inside the code block and ignores it.

In our product documentation, we specify a lot of shell code with pipe characters and would like our customers to be able to easily copy and paste commands from code blocks. As we move our documentation to Docusaurus which uses MDX, this problem arises.

Our current workaround is to use the HTML \<code\> tag, but that's not native markdown and makes our documentation markdown messy.

Do you have any new information on this please?

**Comment by wooorm** [comment]
Docusaurus should update to MDX 2, there is already an issue open about it.

Then the behavior of MDX, with `remark-gfm` (which defines tables), matches exactly how GH handles tables.
